name = "DataFit"
uuid = "980c4361-34be-4910-ad0a-13124148d1e3"
authors = ["Paul Nakroshis <pauln@maine.edu>"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
