name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.9

      - name: Install dependencies
        run: julia -e 'import Pkg; Pkg.instantiate()'
      
      - name: Build
        run: julia --project=@. -e 'import Pkg; Pkg.build()'
      
      - name: Run tests
        run: julia --project=@. -e 'import Pkg; Pkg.test()'
  docs:
    name: Documentation
    runs-on: macos-latest
    permissions:
      contents: write
      statuses: write
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - name: Configure doc environment
        run: |
          julia --project=docs/ -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using DataFit
            DocMeta.setdocmeta!(DataFit, :DocTestSetup, :(using DataFit); recursive=true)
            doctest(DataFit)'
#- name: Upload coverage reports to Codecov
#  uses: codecov/codecov-action@v3
#   env: CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
